### PR TITLE
Search Bar

### PR DESCRIPTION
**Pull request by RepGraphics**
Added Search Bar,
Ability to Search by Author.
Mobile Optimised.

### CODE REVIEW

**Comment by RepGraphics** [comment]
200w

**Comment by prplwtf** [comment]
Could you make a deployment or screen recording so I can see it in action?

**Comment by 0x7d8** [comment]
@prplwtf from blueprint development channel
https://github.com/user-attachments/assets/104c69a2-ad29-4f30-87f3-93d69d01d558

**Comment by RepGraphics** [comment]
https://github.com/user-attachments/assets/13f5d470-6e80-4315-a175-af537997359f

**Pull request merged**
