### PR TITLE
CSS Styling

### PR DESCRIPTION
**Pull request by RepGraphics**
Added Hover Effect to Star On Github:
Star now changes to Github Star Yellow.

Blueprint SVG on Footer:
Icon changes blue on Hover.

SVG Hover may need unique Class or ID if more SVG'S are added that could conflict.

image
image

### CODE REVIEW

**Review by prplwtf — CHANGES_REQUESTED** [review]
First of all, thanks for your contribution! I have a couple changes that I'd like to see before merging this change. 
- Loving the GitHub Star hover effect, everything checks out on that.
- I'm not quite sure about the footer hover effect, as it's not meant to be a button and be pretty much in the background.

**Review by prplwtf — CHANGES_REQUESTED** [review]
Move these changes to `.modules/global/global.css`.

**Comment by prplwtf** [comment]
Could you use the `.star-button` selector instead?

**Comment by prplwtf** [comment]
Was this PR meant to be closed?

**Comment by RepGraphics** [comment]
Nope, i was trying to merge your updated version with mine, and it auto-closed

**Comment by prplwtf** [comment]
Don't think I'm able to reopen this, feel free to open another PR with the aformentioned changes.

**Comment by RepGraphics** [comment]
It should all be sorted, Github app was bugging out aswell so it ended up splitting the commits

**Pull request merged**
